language: java

sudo: required

jdk:
  - oraclejdk8

before_install:
  - chmod +x pip

install:
  - sudo pip install html5validator
 
before_script:
  - npm install -g csslint
  - npm install -g git://github.com/eslint/eslint.git

script: 
  - html5validator --root Fabo/
  - csslint Fabo/
  - eslint Fabo/

git:
  depth: 5